[package]
name = "nicho/wave-survival"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
ecr = "centau/ecr@0.8.0"
signal = "call23re/goodsignal@^0.2.2"
viewport = "aspecky/viewportfitter@^1.0.0"
zonePlus = "mattschrubb/zoneplus@^3.2.0"
reflex = "littensy/reflex@^4.3.1"
sift = "csqrl/sift@0.0.9"
vide = "centau/vide@0.2.0"
janitor = "howmanysmall/janitor@^1.15.7"
spr = "blackjackiee/spr@1.1.3"

[server-dependencies]
profileService = "alreadypro/profileservice@^1.0.4"

[place]
shared-packages = "game.ReplicatedStorage.Packages"