[package]
name = "call23re/goodsignal"
description = "A fast Signal class implementation that has full feature parity with Roblox' RBXScriptSignal"
version = "0.2.2"
license = "MIT"
authors = ["Mark Langen <stravant@gmail.com>", "call23re2"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# None :)